version: '3.8'

services:
  db:
    image: postgres:15.2-alpine3.17
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    volumes:
      - ./tmp/postgres_data:/var/lib/postgresql/data
  redis:
    image: "redis:7.0-alpine3.17"
    ports:
      - 6379:6379
    volumes:
      - ./tmp/redis_data:/var/lib/redis/data
