name: Test Node.js

on:
  push:
    paths:
      - .github/workflows/node-test.yml
      - 'node/*'
  pull_request:
    paths:
      - .github/workflows/node-test.yml
      - 'node/*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read .tool-versions
        uses: marocchino/tool-versions-action@v1
        with:
          path: node/.tool-versions
        id: versions

      - name: Use Node.js ${{ steps.versions.outputs.nodejs}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.versions.outputs.nodejs}}

      - name: Install dependencies
        run: yarn
        working-directory: ./node

      - name: Run tests
        run: yarn test
        working-directory: ./node
